Repository LondonSquad/Novix, pull requests merged in 2025-07, with the labels that each got.

#44 Feature/integrate firebase
  presentation/build.gradle.kts
Labels: enhancement

#46 feature/component/primary-button
  .gitignore
  app/src/main/res/image-add.svg
  designSystem/build.gradle.kts
  designSystem/src/main/java/com/london/designsystem/component/button/LoadingLottieAnimation.kt
  designSystem/src/main/java/com/london/designsystem/component/button/NormalPrimaryButton.kt
  designSystem/src/main/res/drawable-mdpi/icon_add.png
  designSystem/src/main/res/drawable-xhdpi/icon_add.png
  designSystem/src/main/res/drawable-xxhdpi/icon_add.png
  designSystem/src/main/res/drawable-xxxhdpi/icon_add.png
  designSystem/src/main/res/raw/lottie_loading.json
Labels: feature

#53 fix: save icon component
  designSystem/src/main/java/com/london/designsystem/component/SaveIcon.kt
Labels: fix

#54 feat: add home card with loading animation
  designSystem/src/main/java/com/london/designsystem/component/HomeCard.kt
Labels: feature

#69 Hotfix/setup api
  app/src/main/java/com/london/app/di/AppModule.kt
  app/src/main/java/com/london/app/di/DataSourceModule.kt
  app/src/main/java/com/london/app/di/DatabaseModule.kt
  app/src/main/java/com/london/app/di/RepositoryModule.kt
  app/src/main/java/com/london/app/di/ViewModelModule.kt
  data/build.gradle.kts
  data/src/main/java/com/london/data/datasource/local/model/SearchMovieDtoLocal.kt
  data/src/main/java/com/london/data/datasource/local/model/SearchTvShowDtoLocal.kt
  data/src/main/java/com/london/data/datasource/remote/RemoteDataSource.kt
  data/src/main/java/com/london/data/datasource/remote/SearchRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/datasource/remote/search/ApiConstants.kt
  data/src/main/java/com/london/data/datasource/remote/search/RemoteDataSource.kt
  data/src/main/java/com/london/data/datasource/remote/search/SearchMoviesResponseDto.kt
  data/src/main/java/com/london/data/datasource/remote/search/SearchRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/datasource/remote/search/SearchTvShowsResponseDto.kt
  data/src/main/java/com/london/data/datasource/remote/search/model/ApiSearch.kt
  data/src/main/java/com/london/data/datasource/remote/search/model/SearchActorRemote.kt
  data/src/main/java/com/london/data/datasource/remote/search/model/SearchMovieRemote.kt
  data/src/main/java/com/london/data/datasource/remote/search/model/SearchTvShowRemote.kt
  data/src/main/java/com/london/data/mapper/ActorMapper.kt
  data/src/main/java/com/london/data/mapper/MovieMapper.kt
  data/src/main/java/com/london/data/mapper/TvMapper.kt
  data/src/main/java/com/london/data/repository/SearchRepositoryImpl.kt
  data/src/test/java/com/london/data/remote/SearchRemoteDataSourceImplTest.kt
  data/src/test/java/com/london/data/repository/SearchRepositoryImplTest.kt
  defaults.properties
  gradle/libs.versions.toml
Labels: fix

#90 feat: Implement filter functionality for search results
  data/src/main/java/com/london/data/mapper/MovieMapper.kt
  data/src/main/java/com/london/data/mapper/TvMapper.kt
  data/src/test/java/com/london/data/repository/SearchRepositoryImplTest.kt
  designSystem/src/main/java/com/london/designsystem/component/CustomReleasedYearSlider.kt
  designSystem/src/main/java/com/london/designsystem/component/GenreChipGroup.kt
  domain/src/main/java/com/london/domain/entity/Movie.kt
  domain/src/main/java/com/london/domain/entity/TvShow.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetMoviesUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetTvShowsUseCaseTest.kt
  presentation/src/main/java/com/london/presentation/composables/filterbottomsheet/FilterBottomSheet.kt
  presentation/src/main/java/com/london/presentation/composables/filterbottomsheet/FilterButtomSheetUiState.kt
  presentation/src/main/java/com/london/presentation/screen/search/SearchViewModel.kt
  presentation/src/main/java/com/london/presentation/utils/SearchUtils.kt
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#93 refactor: Simplify search logic in SearchViewModel
  presentation/src/main/java/com/london/presentation/screen/search/SearchInteractions.kt
  presentation/src/main/java/com/london/presentation/screen/search/SearchViewModel.kt
Labels: enhancement

#108 Feature/tv shows details screen
  designSystem/src/main/java/com/london/designsystem/component/SaveIcon.kt
  designSystem/src/main/res/values-ar/strings.xml
  designSystem/src/main/res/values/strings.xml
  domain/src/main/java/com/london/domain/usecase/GetImagesById.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetImagesByIdTest.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/tvshowdetails/TvShowDetails.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/tvshowdetails/TvShowDetailsViewModel.kt
  presentation/src/main/java/com/london/presentation/utils/Utils.kt
Labels: enhancement

#134 Refactor: Move API key configuration to local.properties
  .github/workflows/ci.yml
  defaults.properties
Labels: fix

#140 fix: hide filter button for actors category
  presentation/src/main/java/com/london/presentation/screen/search/SearchScreen.kt
  presentation/src/main/java/com/london/presentation/screen/search/SearchUiState.kt
  presentation/src/main/java/com/london/presentation/screen/search/SearchViewModel.kt
Labels: enhancement, fix

#137 Feature/tv shows episode details screen
  app/src/main/java/com/london/app/MainActivity.kt
  app/src/main/java/com/london/app/navigation/NovixApp.kt
  data/src/main/java/com/london/data/datasource/remote/ApiConstants.kt
  data/src/main/java/com/london/data/datasource/remote/details/tvshowdetails/TvShowDetailsRemoteDataSource.kt
  data/src/main/java/com/london/data/datasource/remote/details/tvshowdetails/TvShowDetailsRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/datasource/remote/details/tvshowdetails/model/tvshowepisode/TvShowEpisodeResponse.kt
  data/src/main/java/com/london/data/mapper/tvshowdetails/EpisodesEntity.kt
  data/src/main/java/com/london/data/repository/DetailsRepositoryImpl.kt
  domain/src/main/java/com/london/domain/entity/tvshowdetails/episode/TvShowEpisodeByIdEntity.kt
  domain/src/main/java/com/london/domain/repository/DetailsRepository.kt
  domain/src/main/java/com/london/domain/usecase/GetEpisodeByTvShowId.kt
  presentation/src/main/java/com/london/presentation/composables/ConditionalText.kt
  presentation/src/main/java/com/london/presentation/navigation/Screen.kt
  presentation/src/main/java/com/london/presentation/navigation/arguments/EpisodeDetailsArgs.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/episodedetails/EpisodeDetails.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/episodedetails/EpisodeDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/episodedetails/EpisodeDetailsUiState.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/episodedetails/EpisodeDetailsViewModel.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/tvshowdetails/TvShowDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/tvshowdetails/TvShowDetailsViewModel.kt
  presentation/src/main/java/com/london/presentation/utils/effectListener.kt
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#191 fix: adjust layout properties in actor item
  designSystem/src/main/java/com/london/designsystem/component/ActorItem.kt
Labels: bug

#192 Refactor: Improve FilterBottomSheet responsiveness
  presentation/src/main/java/com/london/presentation/composables/filterbottomsheet/FilterBottomSheet.kt
Labels: bug

#206 feat: add footer section to episode details
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/episodedetails/EpisodeDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/episodedetails/EpisodeDetailsUiState.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/tvshowdetails/TvShowDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/utils/extentions.kt
Labels: feature

#215 Refactor: Create shared DetailsScreenTopBar composable
  designSystem/src/main/java/com/london/designsystem/component/HomeCard.kt
  designSystem/src/main/java/com/london/designsystem/component/SaveIcon.kt
  presentation/src/main/java/com/london/presentation/composables/DetailsScreenTopBar.kt
  presentation/src/main/java/com/london/presentation/screen/details/movieDetalis/MovieDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/tvshowdetails/TvShowDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/tvshowdetails/TvShowDetailsUiState.kt
Labels: fix

#224 Implement movie video fetching functionality
  data/build.gradle.kts
  data/src/main/java/com/london/data/datasource/remote/ApiConstants.kt
  data/src/main/java/com/london/data/datasource/remote/details/moviedetails/MovieDetailsRemoteExceptions.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/movie/MovieVideoProviderRemoteImpl.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/movie/model/MovieVideoProviderRemote.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/movie/model/MovieVideoRemote.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/movie/model/MovieVideoResponse.kt
  data/src/main/java/com/london/data/mapper/videoprovider/movie/MovieVideoMapper.kt
  data/src/main/java/com/london/data/repository/MovieVideoProviderRepositoryImpl.kt
  data/src/main/java/com/london/data/utils/extensions.kt
  data/src/test/java/com/london/data/repository/DetailsRepositoryImplTest.kt
  defaults.properties
  designSystem/src/main/java/com/london/designsystem/component/button/OutlineButton.kt
  designSystem/src/main/java/com/london/designsystem/component/button/PrimaryButton.kt
  domain/src/main/java/com/london/domain/entity/videoprovider/MovieVideo.kt
  domain/src/main/java/com/london/domain/repository/MovieVideoProviderRepository.kt
  domain/src/main/java/com/london/domain/usecase/GetMovieVideoUseCase.kt
  presentation/src/main/java/com/london/presentation/composables/FooterSection.kt
  presentation/src/main/java/com/london/presentation/composables/filterbottomsheet/FilterBottomSheet.kt
  presentation/src/main/java/com/london/presentation/screen/details/movieDetalis/MovieDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/screen/details/movieDetalis/MovieDetailsUiState.kt
  presentation/src/main/java/com/london/presentation/screen/details/movieDetalis/MovieDetailsViewModel.kt
  presentation/src/main/java/com/london/presentation/screen/details/movieDetalis/mapper.kt
  presentation/src/main/java/com/london/presentation/screen/search/SearchScreen.kt
Labels: feature

#228 fix: handle empty image list in tv show details pager
  presentation/src/main/java/com/london/presentation/screen/details/tvshow/tvshowdetails/TvShowDetailsScreen.kt
Labels: bug, fix

#233 fix/image-view
  presentation/src/main/java/com/london/presentation/screen/reviews/ReviewsScreen.kt
Labels: fix

#240 Refactor/replace ktor to retrofit
  app/src/test/java/com/london/data/mapper/videoprovider/movie/MovieVideoMapperKtTest.kt
  data/build.gradle.kts
  data/src/main/java/com/london/data/datasource/remote/details/actordetails/ActorDetailsRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/datasource/remote/details/actordetails/api/ActorDetailsApiService.kt
  data/src/main/java/com/london/data/datasource/remote/details/moviedetails/MovieDetailsRemoteDataSource.kt
  data/src/main/java/com/london/data/datasource/remote/details/moviedetails/MovieDetailsRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/datasource/remote/details/moviedetails/MovieDetailsRemoteImpl.kt
  data/src/main/java/com/london/data/datasource/remote/details/moviedetails/api/MovieDetailsApiService.kt
  data/src/main/java/com/london/data/datasource/remote/details/tvshowdetails/TvShowDetailsRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/datasource/remote/details/tvshowdetails/api/TvShowDetailsApiService.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/movie/MovieVideoProviderRemote.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/movie/MovieVideoProviderRemoteImpl.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/movie/model/MovieVideoProviderRemote.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/movie/model/MovieVideoRemote.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/movie/model/MovieVideoResponse.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/tvshow/TvShowVideoProviderRemote.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/tvshow/TvShowVideoProviderRemoteImpl.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/tvshow/TvShowVideoResponse.kt
  data/src/main/java/com/london/data/datasource/remote/details/videoprovider/tvshow/model/TvShowVideoResponse.kt
  data/src/main/java/com/london/data/datasource/remote/reviews/ReviewsRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/datasource/remote/reviews/api/ReviewsApiService.kt
  data/src/main/java/com/london/data/datasource/remote/search/SearchRemoteDataSource.kt
  data/src/main/java/com/london/data/datasource/remote/search/SearchRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/datasource/remote/search/api/SearchApiService.kt
  data/src/main/java/com/london/data/di/NetworkModule.kt
  data/src/main/java/com/london/data/mapper/videoprovider/movie/MovieVideoMapper.kt
  data/src/main/java/com/london/data/mapper/videoprovider/tvshow/TvShowVideoMapper.kt
  data/src/main/java/com/london/data/repository/MovieDetailsRepoImpl.kt
  data/src/main/java/com/london/data/repository/MovieVideoProviderRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/SearchRepositoryImpl.kt
  data/src/main/java/com/london/data/utils/extensions.kt
  data/src/test/java/com/london/data/datasource/remote/moviedetails/MovieDetailsResponseImplTest.kt
  data/src/test/java/com/london/data/mapper/videoprovider/tvshow/TvShowVideoMapperKtTest.kt
  data/src/test/java/com/london/data/remote/SearchRemoteDataSourceImplTest.kt
  data/src/test/java/com/london/data/repository/MovieDetailsRepoImplTest.kt
  data/src/test/java/com/london/data/repository/MovieVideoProviderRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/SearchRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/TvShowVideoProviderRepositoryImplTest.kt
  data/src/test/java/com/london/data/utils/ExtensionsKtTest.kt
  domain/src/main/java/com/london/domain/repository/DetailsRepository.kt
  domain/src/main/java/com/london/domain/repository/SearchRepository.kt
  domain/src/main/java/com/london/domain/usecase/GetActorsUseCase.kt
  domain/src/main/java/com/london/domain/usecase/GetMoviesByCategoryUseCase.kt
  domain/src/main/java/com/london/domain/usecase/GetMoviesUseCase.kt
  domain/src/main/java/com/london/domain/usecase/GetTvShowsUseCase.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetActorsUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetMoviesByCategoryUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetMoviesUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetTvShowsUseCaseTest.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/london/presentation/screen/category/moviesbycategory/MoviesByCategoryViewModel.kt
  presentation/src/main/java/com/london/presentation/screen/search/SearchViewModel.kt
Labels: fix

#247 feature/login-screen-ui
  designSystem/src/main/java/com/london/designsystem/component/OutlinedTextField.kt
  designSystem/src/main/res/drawable/lock_key.xml
  designSystem/src/main/res/drawable/novix_icon.xml
  designSystem/src/main/res/drawable/polygon1.png
  presentation/src/main/java/com/london/presentation/screen/login/LoginScreen.kt
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#258 Feature/home trending section
  designSystem/src/main/java/com/london/designsystem/color/DarkThemeColors.kt
  designSystem/src/main/java/com/london/designsystem/color/LightThemeColors.kt
  designSystem/src/main/java/com/london/designsystem/color/NovixColor.kt
  presentation/src/main/java/com/london/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/london/presentation/screen/home/TrendingSection.kt
  presentation/src/main/res/drawable/icon_actor.png
  presentation/src/main/res/drawable/icon_movie.png
  presentation/src/main/res/drawable/icon_tvshow.png
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#265 Feature/Add User Authentication
  app/build.gradle.kts
  app/src/main/java/com/london/app/navigation/NovixApp.kt
  data/src/main/java/com/london/data/datasource/common/AuthInterceptor.kt
  data/src/main/java/com/london/data/datasource/common/AuthPreferences.kt
  data/src/main/java/com/london/data/datasource/common/SharedPrefsTokenProvider.kt
  data/src/main/java/com/london/data/datasource/remote/auth/api/AuthApiService.kt
  data/src/main/java/com/london/data/datasource/remote/auth/model/DeleteSessionResponse.kt
  data/src/main/java/com/london/data/datasource/remote/auth/model/GuestSessionResponse.kt
  data/src/main/java/com/london/data/datasource/remote/auth/model/LoginValidationRequestBody.kt
  data/src/main/java/com/london/data/datasource/remote/auth/model/RequestTokenResponse.kt
  data/src/main/java/com/london/data/datasource/remote/auth/model/SessionResponse.kt
  data/src/main/java/com/london/data/datasource/remote/auth/model/Token.kt
  data/src/main/java/com/london/data/datasource/remote/auth/model/ValidateKeyResponse.kt
  data/src/main/java/com/london/data/di/NetworkModule.kt
  data/src/main/java/com/london/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/london/domain/repository/AuthRepository.kt
  domain/src/main/java/com/london/domain/repository/SessionTokenProvider.kt
  domain/src/main/java/com/london/domain/usecase/login/LoginAsGuestUseCase.kt
  domain/src/main/java/com/london/domain/usecase/login/LoginUseCase.kt
  domain/src/main/java/com/london/domain/usecase/login/LogoutUseCase.kt
  domain/src/main/java/com/london/domain/usecase/login/StartWebAuthUseCase.kt
  presentation/src/main/java/com/london/presentation/navigation/Screen.kt
  presentation/src/main/java/com/london/presentation/screen/login/LoginContract.kt
  presentation/src/main/java/com/london/presentation/screen/login/LoginEffect.kt
  presentation/src/main/java/com/london/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/london/presentation/screen/login/LoginUiState.kt
  presentation/src/main/java/com/london/presentation/screen/login/LoginViewModel.kt
Labels: feature

#271 refactor/remote-data-source-for-review-and-popular
  data/src/main/java/com/london/data/datasource/remote/home/popular/PopularRemoteDataSource.kt
  data/src/main/java/com/london/data/datasource/remote/home/popular/PopularRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/datasource/remote/home/popular/api/PopularApiService.kt
  data/src/main/java/com/london/data/datasource/remote/reviews/ReviewsRemoteDataSource.kt
  data/src/main/java/com/london/data/datasource/remote/reviews/ReviewsRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/datasource/remote/reviews/api/ReviewsApiService.kt
  data/src/main/java/com/london/data/repository/DetailsRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/popular/PopularRepositoryImpl.kt
  data/src/test/java/com/london/data/repository/DetailsRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/popular/PopularRepositoryImplTest.kt
Labels: enhancement

#298 refactor: organize top-rated feature files
  data/src/main/java/com/london/data/di/NetworkModule.kt
  data/src/main/java/com/london/data/mapper/toprated/TopRatedMovieMapper.kt
  data/src/main/java/com/london/data/mapper/toprated/TopRatedTvSeriesMapper.kt
  data/src/main/java/com/london/data/remote/model/toprated/TopRatedMovieRemote.kt
  data/src/main/java/com/london/data/remote/model/toprated/TopRatedTvSeriesRemote.kt
  data/src/main/java/com/london/data/remote/service/toprated/TopRatedMovieApiService.kt
  data/src/main/java/com/london/data/remote/service/toprated/TopRatedTvSeriesApiService.kt
  data/src/main/java/com/london/data/remote/source/toprated/movie/TopRatedMovieRemoteDataSource.kt
  data/src/main/java/com/london/data/remote/source/toprated/movie/TopRatedMovieRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/remote/source/toprated/tvseries/TopRatedTvRemoteDataSource.kt
  data/src/main/java/com/london/data/remote/source/toprated/tvseries/TopRatedTvRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/repository/toprated/TopRatedMovieRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/toprated/TopRatedTvSeriesRepositoryImpl.kt
  data/src/test/java/com/london/data/repository/TopRatedMovieRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/TopRatedTvSeriesRepositoryImplTest.kt
  domain/src/main/java/com/london/domain/repository/toprated/TopRatedMovieRepository.kt
  domain/src/main/java/com/london/domain/repository/toprated/TopRatedTvSeriesRepository.kt
  domain/src/main/java/com/london/domain/usecase/toprated/GetTopRatedMoviesUseCase.kt
  domain/src/main/java/com/london/domain/usecase/toprated/GetTopRatedTvSeriesUseCase.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetTopRatedMoviesUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetTopRatedTvSeriesUseCaseTest.kt
  presentation/src/main/java/com/london/presentation/feature/toprated/TopRatedViewModel.kt
Labels: enhancement

#374 fix: issues from 38 to 42
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/gallery/ActorGalleryScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/tvshow/episodedetails/EpisodeDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/tvshow/tvshowdetails/TvShowDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/toprated/TopRatedScreen.kt
Labels: fix

#351 hotfix: unit-test-packaging
  app/src/test/java/com/london/domain/usecase/login/LoginAsGuestUseCaseTest.kt
  data/src/main/java/com/london/data/local/preference/AppPreferencesServiceImpl.kt
  data/src/test/java/com/london/data/local/preference/AppPreferencesServiceImplTest.kt
  data/src/test/java/com/london/data/mapper/ActorMapperKtTest.kt
  data/src/test/java/com/london/data/mapper/movie/MovieVideoMapperKtTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/login/LoginAsGuestUseCaseTest.kt
Labels: enhancement, fix

#383 hotfix/tab-layout
  designSystem/src/main/java/com/london/designsystem/component/TabLayout.kt
Labels: fix

#384 hotfix/navigation-app
  app/src/main/java/com/london/app/navigation/NovixApp.kt
Labels: bug

#391 fix: issues from 43, 46, 47, 48, 49, 58
  designSystem/src/main/java/com/london/designsystem/color/DarkThemeColors.kt
  designSystem/src/main/java/com/london/designsystem/color/LightThemeColors.kt
  designSystem/src/main/java/com/london/designsystem/color/NovixColor.kt
  designSystem/src/main/java/com/london/designsystem/component/button/ErrorImageBox.kt
  designSystem/src/main/res/values/strings.xml
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/gallery/ActorGalleryScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/movieDetalis/MovieDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/shared/CustomBackDropImagePager.kt
Labels: fix

#409 Top Tv Shows picks UI
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/topmoviespicks/TopMoviesPicksContract.kt
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/topmoviespicks/TopMoviesPicksScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/topmoviespicks/TopMoviesPicksViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/toptvshowspicks/TopTvShowsPicksContract.kt
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/toptvshowspicks/TopTvShowsPicksScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/toptvshowspicks/TopTvShowsPicksUiState.kt
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/toptvshowspicks/TopTvShowsPicksViewModel.kt
  presentation/src/main/java/com/london/presentation/shared/MediaLazyGrid.kt
Labels: bug, fix

#420 feat: Add RTL support to PopularSection
  designSystem/src/main/java/com/london/designsystem/color/DarkThemeColors.kt
  designSystem/src/main/java/com/london/designsystem/color/LightThemeColors.kt
  presentation/src/main/java/com/london/presentation/feature/home/PopularSection.kt
Labels: bug

#429 Feature No network screen Movie & Tv Show trending
  presentation/src/main/java/com/london/presentation/feature/home/trending/actor/TrendingActorsContract.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/actor/TrendingActorsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/actor/TrendingActorsViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/movies/TrendingMoviesContract.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/movies/TrendingMoviesScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/movies/TrendingMoviesViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/tvshows/TrendingTvShowsContract.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/tvshows/TrendingTvShowsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/tvshows/TrendingTvShowsViewModel.kt
  presentation/src/main/java/com/london/presentation/shared/LazyPagingColumn.kt
  presentation/src/main/java/com/london/presentation/shared/MediaLazyPagingGrid.kt
Labels: feature

#433 Hotfix actors details screen
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsScreen.kt
Labels: bug

#441 feat: Update CircularLoading component with wavy animation
  designSystem/src/main/java/com/london/designsystem/component/CircularLoading.kt
Labels: enhancement

#349 Refactor: Improve data mapping and local data source handling
  data/src/main/java/com/london/data/di/DataBaseModule.kt
  data/src/main/java/com/london/data/local/database/convertor/SearchActorsConvertor.kt
  data/src/main/java/com/london/data/local/database/convertor/SearchMoviesConverter.kt
  data/src/main/java/com/london/data/local/database/convertor/SearchTvShowConvertor.kt
  data/src/main/java/com/london/data/local/model/search/SearchActorsDtoLocal.kt
  data/src/main/java/com/london/data/local/model/search/SearchMovieDtoLocal.kt
  data/src/main/java/com/london/data/local/model/search/SearchTvShowDtoLocal.kt
  data/src/main/java/com/london/data/local/source/LocalDataSource.kt
  data/src/main/java/com/london/data/local/source/search/ActorLocalDataSourceImpl.kt
  data/src/main/java/com/london/data/local/source/search/MovieLocalDataSourceImpl.kt
  data/src/main/java/com/london/data/local/source/search/TvShowLocalDataSourceImpl.kt
  data/src/main/java/com/london/data/mapper/ActorMapper.kt
  data/src/main/java/com/london/data/mapper/MovieMapper.kt
  data/src/main/java/com/london/data/mapper/TvMapper.kt
  data/src/main/java/com/london/data/mapper/moviedetails/ActorMapper.kt
  data/src/main/java/com/london/data/mapper/recent/recentWatchedMapper.kt
  data/src/main/java/com/london/data/mapper/trending/TrendingActorMapper.kt
  data/src/main/java/com/london/data/mapper/tvshowdetails/EpisodesEntity.kt
  data/src/main/java/com/london/data/remote/model/search/model/SearchMovieRemote.kt
  data/src/main/java/com/london/data/remote/model/search/model/SearchTvShowRemote.kt
  data/src/main/java/com/london/data/remote/model/search/model/searchactormodel/KnownFor.kt
  data/src/main/java/com/london/data/remote/model/search/model/searchactormodel/SearchActorRemote.kt
  data/src/main/java/com/london/data/remote/service/search/SearchApiService.kt
  data/src/main/java/com/london/data/remote/source/search/SearchRemoteDataSource.kt
  data/src/main/java/com/london/data/remote/source/search/SearchRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/repository/DetailsRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/MovieDetailsRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/SearchRepositoryImpl.kt
  data/src/main/java/com/london/data/utils/FetchAndSync.kt
  data/src/main/java/com/london/data/utils/extensions.kt
  data/src/test/java/com/london/data/mapper/ActorMapperKtTest.kt
  data/src/test/java/com/london/data/mapper/trending/TrendingActorMapperTest.kt
  data/src/test/java/com/london/data/repository/SearchRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/TrendingRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/recent/RecentWatchedRepositoryImlTest.kt
  domain/src/main/java/com/london/domain/entity/Actor.kt
  domain/src/main/java/com/london/domain/entity/Movie.kt
  domain/src/main/java/com/london/domain/usecase/details/movie/GetFirstTenMovieImagesUseCase.kt
  domain/src/test/kotlin/com/london/domain/usecase/AddMovieToRecentWatchedUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetActorsUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetFirstTenMovieImagesUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetMovieCastUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetMoviesByCategoryUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetMoviesUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetRecentWatchedMoviesUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetSimilarMoviesUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetTrendingActorsUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetUpComingMoviesByCategoryUseCaseTest.kt
  presentation/src/main/java/com/london/presentation/feature/category/moviesbycategory/MoviesByCategoryScreen.kt
  presentation/src/main/java/com/london/presentation/feature/continuewatching/ContinueWatchingScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/movieDetalis/MovieDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/movieDetalis/MovieDetailsViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/details/tvshow/episodedetails/EpisodeDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/HomeScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/mapper.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/actor/TrendingActorsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/search/mediaToRecentViewedMapper.kt
  presentation/src/main/java/com/london/presentation/shared/ActorsLayout.kt
  presentation/src/main/java/com/london/presentation/shared/MoviesLayout.kt
Labels: enhancement

#457 localize: update Arabic translations
  presentation/src/main/res/values-ar/strings.xml
Labels: bug

#468 Refactor Actors details Screen
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsScreen.kt
Labels: bug

#477 Add extension to trim excessive spaces
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/utils/extentions.kt
Labels: bug
