Repository LondonSquad/Novix, pull requests merged in 2025-08, with the labels that each got.

#487 refactor: enhance ActorInfoSection layout and styling
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsScreen.kt
Labels: bug, fix

#488 refactor/onboarding-scroll-and-status-bar
  .gitignore
  app/src/main/java/com/london/app/MainActivity.kt
  presentation/src/main/java/com/london/presentation/feature/onboarding/WelcomeScreen.kt
  presentation/src/main/res/drawable-hdpi/img_onboarding_first.png
  presentation/src/main/res/drawable-hdpi/img_onboarding_fourth.png
  presentation/src/main/res/drawable-hdpi/img_onboarding_second.png
  presentation/src/main/res/drawable-hdpi/img_onboarding_third.png
  presentation/src/main/res/drawable-mdpi/img_onboarding_first.png
  presentation/src/main/res/drawable-mdpi/img_onboarding_fourth.png
  presentation/src/main/res/drawable-mdpi/img_onboarding_second.png
  presentation/src/main/res/drawable-mdpi/img_onboarding_third.png
  presentation/src/main/res/drawable-xhdpi/img_onboarding_first.png
  presentation/src/main/res/drawable-xhdpi/img_onboarding_fourth.png
  presentation/src/main/res/drawable-xhdpi/img_onboarding_second.png
  presentation/src/main/res/drawable-xhdpi/img_onboarding_third.png
  presentation/src/main/res/drawable-xxhdpi/img_onboarding_first.png
  presentation/src/main/res/drawable-xxhdpi/img_onboarding_fourth.png
  presentation/src/main/res/drawable-xxhdpi/img_onboarding_second.png
  presentation/src/main/res/drawable-xxhdpi/img_onboarding_third.png
  presentation/src/main/res/drawable-xxxhdpi/img_onboarding_fourth.png
  presentation/src/main/res/drawable/img_onboarding_first.webp
  presentation/src/main/res/drawable/img_onboarding_second.webp
  presentation/src/main/res/drawable/img_onboarding_third.webp
  presentation/src/main/res/drawable/welcome_screen_dark.webp
  presentation/src/main/res/drawable/welcome_screen_light.webp
Labels: bug, enhancement, fix

#493 fix: Adjust spacing and item size in HomeScreen
  presentation/src/main/java/com/london/presentation/feature/home/HomeScreen.kt
  presentation/src/main/java/com/london/presentation/shared/GenresSection.kt
Labels: bug

#495 Feature empty actor details screen
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsContract.kt
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsUiState.kt
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsViewModel.kt
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: bug, enhancement

#501 hotfix/movie-time
  presentation/src/main/java/com/london/presentation/feature/details/movieDetalis/MovieDetailsScreen.kt
Labels: fix

#537 refactor: move actor top picks use cases to toppicks package
  domain/src/main/java/com/london/domain/usecase/toppicks/GetActorMoviePicksByIdUseCase.kt
  domain/src/main/java/com/london/domain/usecase/toppicks/GetActorTvShowPicksByIdUseCase.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetActorMoviePicksByIdUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetActorTvShowPicksByIdUseCaseTest.kt
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/topmoviespicks/TopMoviesPicksViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/details/actordetails/toptvshowspicks/TopTvShowsPicksViewModel.kt
Labels: fix

#539 Feature/appearance mode
  app/src/main/java/com/london/app/MainActivity.kt
  data/src/main/java/com/london/data/local/preference/AppPreferencesServiceImpl.kt
  domain/src/main/java/com/london/domain/theme/AppTheme.kt
  presentation/src/main/java/com/london/presentation/feature/account/AccountContract.kt
  presentation/src/main/java/com/london/presentation/feature/account/AccountScreen.kt
  presentation/src/main/java/com/london/presentation/feature/account/AccountViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/account/appearance/AppearanceBottomSheet.kt
  presentation/src/main/java/com/london/presentation/feature/account/state/AccountUiState.kt
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#538 feat: Make ContinueWatchingScreen title customizable
  app/src/main/java/com/london/app/navigation/NovixApp.kt
  presentation/src/main/java/com/london/presentation/feature/continuewatching/ContinueWatchingScreen.kt
  presentation/src/main/java/com/london/presentation/feature/continuewatching/ContinueWatchingUiState.kt
  presentation/src/main/java/com/london/presentation/feature/continuewatching/ContinueWatchingViewModel.kt
Labels: feature

#549 Fix/account screen navigation after logout
  app/src/main/java/com/london/app/navigation/NovixApp.kt
  data/src/main/java/com/london/data/remote/model/authentication/SessionId.kt
  data/src/main/java/com/london/data/remote/service/authentication/AuthenticationApiService.kt
  data/src/main/java/com/london/data/remote/source/authentication/AuthenticationRemoteDataSource.kt
  data/src/main/java/com/london/data/remote/source/authentication/AuthenticationRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/repository/authentication/AuthenticationRepositoryImpl.kt
  data/src/test/java/com/london/data/repository/AuthRepositoryImplTest.kt
  presentation/src/main/java/com/london/presentation/feature/account/AccountEffect.kt
  presentation/src/main/java/com/london/presentation/feature/account/AccountScreen.kt
  presentation/src/main/java/com/london/presentation/feature/account/AccountViewModel.kt
Labels: fix

#530 Feature/movie rating presentation
  app/src/main/java/com/london/app/navigation/NovixApp.kt
  data/src/main/java/com/london/data/di/NetworkModule.kt
  data/src/main/java/com/london/data/di/RemoteDataSourceModule.kt
  data/src/main/java/com/london/data/di/RepositoryModule.kt
  data/src/main/java/com/london/data/local/preference/AuthPreferences.kt
  data/src/main/java/com/london/data/mapper/details/movie/MovieAccountStatesMapper.kt
  data/src/main/java/com/london/data/remote/model/details/movie/model/moviedetails/AccountMovieStatesResponse.kt
  data/src/main/java/com/london/data/remote/service/details/movie/MovieDetailsApiService.kt
  data/src/main/java/com/london/data/remote/service/details/rating/RatingApiService.kt
  data/src/main/java/com/london/data/remote/source/details/movie/MovieDetailsRemoteDataSource.kt
  data/src/main/java/com/london/data/remote/source/details/movie/MovieDetailsRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/remote/source/details/rating/RatingRemoteDataSource.kt
  data/src/main/java/com/london/data/remote/source/details/rating/RatingRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/repository/rating/RatingRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/search/MovieDetailsRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/search/TvShowRepositoryImpl.kt
  data/src/main/java/com/london/data/utils/extensions.kt
  data/src/test/java/com/london/data/repository/MovieDetailsRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/RatingRepositoryImplTest.kt
  designSystem/src/main/java/com/london/designsystem/component/GuestUserLoginBottomSheet.kt
  designSystem/src/main/java/com/london/designsystem/component/RatingBottomSheet.kt
  designSystem/src/main/res/drawable/ic_close.xml
  designSystem/src/main/res/drawable/ic_star_filled.xml
  designSystem/src/main/res/drawable/ic_star_outline.xml
  designSystem/src/main/res/drawable/user_person_profile.xml
  designSystem/src/main/res/values-ar/strings.xml
  designSystem/src/main/res/values/strings.xml
  domain/src/main/java/com/london/domain/entity/moviedatails/MovieStates.kt
  domain/src/main/java/com/london/domain/repository/MovieDetailsRepository.kt
  domain/src/main/java/com/london/domain/repository/RatingRepository.kt
  domain/src/main/java/com/london/domain/usecase/AddMovieRatingByIdUseCase.kt
  domain/src/main/java/com/london/domain/usecase/GetAccountMovieStatesById.kt
  domain/src/test/kotlin/com/london/domain/usecase/AddMovieRatingByIdUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/GetMovieRatingByIdUseCaseTest.kt
  presentation/src/main/java/com/london/presentation/feature/details/movieDetalis/MovieDetailsContract.kt
  presentation/src/main/java/com/london/presentation/feature/details/movieDetalis/MovieDetailsEffect.kt
  presentation/src/main/java/com/london/presentation/feature/details/movieDetalis/MovieDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/movieDetalis/MovieDetailsUiState.kt
  presentation/src/main/java/com/london/presentation/feature/details/movieDetalis/MovieDetailsViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/details/tvshow/episodedetails/EpisodeDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/tvshow/tvshowdetails/TvShowDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/login/LoginScreen.kt
  presentation/src/main/java/com/london/presentation/shared/FooterSection.kt
  presentation/src/main/java/com/london/presentation/shared/SnackBarAnimation.kt
Labels: feature

#568 Account Id
  data/src/main/java/com/london/data/di/RepositoryModule.kt
  data/src/main/java/com/london/data/local/preference/AuthPreferences.kt
  data/src/main/java/com/london/data/repository/authentication/AuthenticationRepositoryImpl.kt
  data/src/test/java/com/london/data/repository/AuthRepositoryImplTest.kt
  domain/src/main/java/com/london/domain/repository/AuthRepository.kt
Labels: feature

#572 fix: open change password in browser and update gradle
  data/src/test/java/com/london/data/local/preference/AppPreferencesServiceImplTest.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  presentation/src/main/java/com/london/presentation/feature/account/AccountEffect.kt
  presentation/src/main/java/com/london/presentation/feature/account/AccountViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/account/accountScreen.kt
Labels: bug

#581 Feature/remove unused dependencies in gradle
  gradle/libs.versions.toml
Labels: enhancement

#594 Add unit tests for category ViewModels
  app/src/main/java/com/london/app/navigation/NovixApp.kt
  presentation/src/main/java/com/london/presentation/feature/category/main/CategoryScreen.kt
  presentation/src/main/java/com/london/presentation/feature/category/movie/MovieCategoryViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/category/tvshow/TvShowCategoryViewModel.kt
  presentation/src/test/java/com/london/presentation/feature/category/movie/MovieCategoryViewModelTest.kt
  presentation/src/test/java/com/london/presentation/feature/category/tvshow/TvShowCategoryViewModelTest.kt
  presentation/src/test/java/com/london/presentation/feature/details/tvshow/info/TvShowDetailsViewModelTest.kt
Labels: Task

#590 Refactor/movie details
  data/src/main/java/com/london/data/mapper/details/movie/MovieImagesMapper.kt
  data/src/main/java/com/london/data/repository/search/MovieDetailsRepositoryImpl.kt
  data/src/test/java/com/london/data/repository/MovieDetailsRepositoryImplTest.kt
  domain/src/main/java/com/london/domain/entity/moviedatails/MovieImages.kt
  domain/src/main/java/com/london/domain/entity/moviedatails/Poster.kt
  domain/src/main/java/com/london/domain/repository/MovieDetailsRepository.kt
  domain/src/main/java/com/london/domain/usecase/details/movie/ManageMovieDetailsUseCase.kt
  domain/src/test/kotlin/com/london/domain/usecase/details/movie/ManageMovieDetailsUseCaseTest.kt
  presentation/src/main/java/com/london/presentation/feature/details/movie/MovieDetailsViewModel.kt
Labels: fix

#624 refactor/authentication
  app/src/main/java/com/london/app/navigation/NovixApp.kt
  app/src/test/java/com/london/domain/usecase/rating/RatingUseCaseTest.kt
  data/src/main/java/com/london/data/di/NetworkModule.kt
  data/src/main/java/com/london/data/di/RemoteDataSourceModule.kt
  data/src/main/java/com/london/data/di/RepositoryModule.kt
  data/src/main/java/com/london/data/local/preference/AuthenticationPreferences.kt
  data/src/main/java/com/london/data/local/preference/SharedPrefsTokenProvider.kt
  data/src/main/java/com/london/data/remote/interceptor/AuthenticationInterceptor.kt
  data/src/main/java/com/london/data/remote/model/ApiConstants.kt
  data/src/main/java/com/london/data/remote/model/authentication/LoginRequest.kt
  data/src/main/java/com/london/data/remote/model/authentication/RequestToken.kt
  data/src/main/java/com/london/data/remote/service/authentication/AuthenticationApiService.kt
  data/src/main/java/com/london/data/remote/source/authentication/AuthenticationRemoteDataSource.kt
  data/src/main/java/com/london/data/remote/source/authentication/AuthenticationRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/repository/account/AccountRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/authentication/AuthenticationRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/list/CustomMovieListRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/movie/MovieRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/recent/RecentWatchedRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/tvshow/TvShowRepositoryImpl.kt
  data/src/test/java/com/london/data/repository/AuthenticationRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/MovieRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/TvShowRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/account/AccountRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/list/CustomMovieListRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/recent/RecentWatchedRepositoryImplTest.kt
  domain/src/main/java/com/london/domain/repository/AccountRepository.kt
  domain/src/main/java/com/london/domain/repository/AuthenticationRepository.kt
  domain/src/main/java/com/london/domain/usecase/authentication/AuthenticationUseCase.kt
  domain/src/test/kotlin/com/london/domain/usecase/login/AuthenticationUseCaseTest.kt
  presentation/src/main/java/com/london/presentation/feature/authentication/login/LoginEffect.kt
  presentation/src/main/java/com/london/presentation/feature/authentication/login/LoginScreen.kt
  presentation/src/main/java/com/london/presentation/feature/authentication/login/LoginViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/authentication/register/RegisterViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/authentication/register/RegistrationScreen.kt
  presentation/src/main/java/com/london/presentation/feature/authentication/register/RegistrationUiState.kt
  presentation/src/main/java/com/london/presentation/feature/authentication/register/RegistrationViewModel.kt
  presentation/src/test/java/com/london/presentation/feature/authentication/login/LoginViewModelTest.kt
  presentation/src/test/java/com/london/presentation/feature/authentication/register/RegistrationViewModelTest.kt
Labels: enhancement

#542 New Composables to clear duplicate code presentation
  designSystem/src/main/java/com/london/designsystem/component/TabLayout.kt
  designSystem/src/main/java/com/london/designsystem/component/button/ErrorImageBox.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/actor/info/gallery/ActorsGalleryScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/movie/MovieDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/tvshow/info/tvShowDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/continuewatching/ContinueWatchingScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/popular/PopularSection.kt
  presentation/src/main/java/com/london/presentation/feature/home/section/CarouselSection.kt
  presentation/src/main/java/com/london/presentation/feature/home/toprated/TopRatedScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/upcoming/upcomingSection.kt
  presentation/src/main/java/com/london/presentation/feature/reviews/reviewsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/search/SearchScreen.kt
  presentation/src/main/java/com/london/presentation/shared/ActorItem.kt
  presentation/src/main/java/com/london/presentation/shared/CategoryItem.kt
  presentation/src/main/java/com/london/presentation/shared/CustomBackDropImagePager.kt
  presentation/src/main/java/com/london/presentation/shared/DefaultAppTopBar.kt
  presentation/src/main/java/com/london/presentation/shared/HomeCard.kt
  presentation/src/main/java/com/london/presentation/shared/MediaGenreFilters.kt
  presentation/src/main/java/com/london/presentation/shared/MediaLazyGrid.kt
  presentation/src/main/java/com/london/presentation/shared/MediaLazyPagingGrid.kt
  presentation/src/main/java/com/london/presentation/shared/MoviesLayout.kt
  presentation/src/main/java/com/london/presentation/shared/TvShowsLayout.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaGridConfig.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaLazyGridWithFilter.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaLazyGridWithTabs.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaLazyVerticalGrid.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaTypeUtils.kt
Labels: feature

#639 Add animation to MediaLazyVerticalGrid
  presentation/src/main/java/com/london/presentation/shared/container/MediaLazyGridWithFilter.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaLazyGridWithTabs.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaLazyVerticalGrid.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaTypeUtils.kt
Labels: feature

#640 refactor/navigation
  app/src/main/java/com/london/app/MainActivity.kt
  app/src/main/java/com/london/app/navigation/AppNavGraph.kt
  app/src/main/java/com/london/app/navigation/NavHostGraph.kt
  app/src/main/java/com/london/app/navigation/NovixApp.kt
  app/src/main/java/com/london/app/navigation/appDestination.kt
  app/src/main/java/com/london/app/navigation/graph/authNavGraph.kt
  app/src/main/java/com/london/app/navigation/graph/mainNavGraph.kt
  app/src/main/java/com/london/app/navigation/graph/onboardingNavGraph.kt
  app/src/main/java/com/london/app/navigation/graph/splashNavGraph.kt
  app/src/main/java/com/london/app/navigation/navExtensions.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingScreen.kt
  presentation/src/main/java/com/london/presentation/feature/authentication/login/LoginScreen.kt
  presentation/src/main/java/com/london/presentation/feature/authentication/register/RegistrationScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/actor/ActorDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/movie/MovieDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/tvshow/episode/episodeDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/details/tvshow/info/tvShowDetailsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/HomeScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/continuewatching/ContinueWatchingScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/toprated/TopRatedScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/actor/TrendingActorsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/movie/TrendingMoviesScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/tvshow/TrendingTvShowsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/list/savedlist/listScreen.kt
Labels: enhancement

#632 Refactor my rating feature
  data/src/main/java/com/london/data/repository/tvshow/TvShowRepositoryImpl.kt
  data/src/test/java/com/london/data/repository/TvShowRepositoryImplTest.kt
  domain/src/main/java/com/london/domain/repository/TvShowRepository.kt
  domain/src/main/java/com/london/domain/usecase/rating/ManageRatingUseCase.kt
  domain/src/test/kotlin/com/london/domain/usecase/rating/ManageRatingUseCaseTest.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingEffect.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingScreen.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingUiState.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingsContract.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingsViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/details/tvshow/info/TvShowDetailsViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/home/continuewatching/ContinueWatchingScreen.kt
  presentation/src/main/java/com/london/presentation/shared/HomeCard.kt
  presentation/src/main/java/com/london/presentation/shared/MediaLazyGrid.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaGridConfig.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaLazyGridWithFilter.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaLazyGridWithTabs.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaLazyVerticalGrid.kt
  presentation/src/main/java/com/london/presentation/shared/container/MediaTypeUtils.kt
  presentation/src/main/res/values/strings.xml
  presentation/src/test/java/com/london/presentation/feature/account/rating/MyRatingsViewModelTest.kt
  presentation/src/test/java/com/london/presentation/feature/details/tvshow/info/TvShowDetailsViewModelTest.kt
Labels: enhancement

#659 refactor/reviews
  domain/src/main/java/com/london/domain/usecase/details/tvshow/GetTvShowUseCase.kt
  presentation/src/main/java/com/london/presentation/feature/reviews/ReviewsDimens.kt
  presentation/src/main/java/com/london/presentation/feature/reviews/ReviewsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/reviews/ReviewsViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/reviews/reviewsScreen.kt
  presentation/src/main/java/com/london/presentation/shared/ReviewsDate.kt
  presentation/src/main/java/com/london/presentation/shared/base/BasePagingSource.kt
  presentation/src/test/java/com/london/presentation/feature/reviews/ReviewsViewModelTest.kt
Labels: enhancement, refactor

#634 refactor/trending
  app/src/main/java/com/london/app/navigation/graph/mainNavGraph.kt
  domain/src/main/java/com/london/domain/usecase/details/movie/GetMovieUseCase.kt
  domain/src/main/java/com/london/domain/usecase/details/tvshow/GetTvEpisodesUseCase.kt
  domain/src/main/java/com/london/domain/usecase/details/tvshow/GetTvShowUseCase.kt
  domain/src/test/kotlin/com/london/domain/usecase/details/movie/GetMovieUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/details/tvshow/GetTvEpisodesUseCaseTest.kt
  domain/src/test/kotlin/com/london/domain/usecase/details/tvshow/GetTvShowUseCaseTest.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/TrendingCategories.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/actor/TrendingActorsContract.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/actor/TrendingActorsEffect.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/actor/TrendingActorsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/actor/TrendingActorsUiState.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/actor/TrendingActorsViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/movie/TrendingMoviesContract.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/movie/TrendingMoviesEffect.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/movie/TrendingMoviesScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/movie/TrendingMoviesUiState.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/movie/TrendingMoviesViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/tvshow/TrendingTvShowsContract.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/tvshow/TrendingTvShowsEffect.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/tvshow/TrendingTvShowsScreen.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/tvshow/TrendingTvShowsUiState.kt
  presentation/src/main/java/com/london/presentation/feature/home/trending/tvshow/TrendingTvShowsViewModel.kt
  presentation/src/main/java/com/london/presentation/shared/GenresSection.kt
  presentation/src/main/java/com/london/presentation/shared/base/BasePagingSource.kt
  presentation/src/test/java/com/london/presentation/feature/home/continuewatching/ContinueWatchingViewModelTest.kt
  presentation/src/test/java/com/london/presentation/feature/home/trending/actor/TrendingActorsViewModelTest.kt
  presentation/src/test/java/com/london/presentation/feature/home/trending/movie/TrendingMoviesViewModelTest.kt
  presentation/src/test/java/com/london/presentation/feature/home/trending/tvshow/TrendingTvShowsViewModelTest.kt
Labels: enhancement

#641 Refactor Search Feature
  data/src/main/java/com/london/data/local/model/recent/search/RecentSearchLocal.kt
  data/src/main/java/com/london/data/mapper/recent/RecentSearchMapper.kt
  data/src/test/java/com/london/data/repository/recent/RecentRepositoryImplTest.kt
  domain/src/main/java/com/london/domain/entity/recent/RecentSearch.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingContract.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingEffect.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingScreen.kt
  presentation/src/main/java/com/london/presentation/feature/account/rating/MyRatingViewModel.kt
  presentation/src/main/java/com/london/presentation/feature/search/MovieUi.kt
  presentation/src/main/java/com/london/presentation/feature/search/SearchContract.kt
  presentation/src/main/java/com/london/presentation/feature/search/SearchEffect.kt
  presentation/src/main/java/com/london/presentation/feature/search/SearchScreen.kt
  presentation/src/main/java/com/london/presentation/feature/search/SearchUiState.kt
  presentation/src/main/java/com/london/presentation/feature/search/SearchViewModel.kt
  presentation/src/test/java/com/london/presentation/feature/account/rating/MyRatingViewModelTest.kt
Labels: enhancement

#694 hotfix/unused-utils and refactor app nav
  app/src/main/java/com/london/app/di/DataModule.kt
  app/src/main/java/com/london/app/navigation/NavHostGraph.kt
  app/src/main/java/com/london/app/navigation/NovixApp.kt
  app/src/main/java/com/london/app/navigation/appDestination.kt
  app/src/main/java/com/london/app/navigation/graph/mainNavGraph.kt
  data/src/main/java/com/london/data/local/database/convertor/CommonConverter.kt
  data/src/main/java/com/london/data/local/exception/LocalDataSourceExceptions.kt
  data/src/main/java/com/london/data/local/preference/AppLanguage.kt
  data/src/main/java/com/london/data/local/preference/AppPreferencesServiceImpl.kt
  data/src/main/java/com/london/data/local/source/home/popular/PopularLocalDataSourceImpl.kt
  data/src/main/java/com/london/data/local/source/home/toprated/TopRatedDataSourceImpl.kt
  data/src/main/java/com/london/data/local/utils/daoUtils.kt
  data/src/main/java/com/london/data/local/utils/jsonList.kt
  data/src/main/java/com/london/data/utils/FromJsonList.kt
  data/src/main/java/com/london/data/utils/constants.kt
  designSystem/src/main/java/com/london/designsystem/component/AppNavBar.kt
Labels: enhancement, feature

#718 Refactor data - domain
  ImageHaramBlur/src/main/java/com/london/imageharamblur/utils/bitmapBlur.kt
  ImageHaramBlur/src/main/java/com/london/imageharamblur/utils/bitmapUtils.kt
  data/src/main/java/com/london/data/local/preference/appLanguage.kt
  data/src/main/java/com/london/data/local/source/home/popular/PopularLocalDataSourceImpl.kt
  data/src/main/java/com/london/data/local/source/home/toprated/TopRatedDataSourceImpl.kt
  data/src/main/java/com/london/data/local/source/home/upcoming/UpComingLocalDataSourceImpl.kt
  data/src/main/java/com/london/data/local/utils/jsonList.kt
  data/src/main/java/com/london/data/remote/model/ApiConstants.kt
  data/src/main/java/com/london/data/remote/model/toprated/TopRatedMovieRemote.kt
  data/src/main/java/com/london/data/remote/model/toprated/TopRatedTvShowRemote.kt
  data/src/main/java/com/london/data/remote/service/account/AccountApiService.kt
  data/src/main/java/com/london/data/remote/source/account/AccountRemoteDataSource.kt
  data/src/main/java/com/london/data/remote/source/account/AccountRemoteDataSourceImpl.kt
  data/src/main/java/com/london/data/repository/account/AccountRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/authentication/AuthenticationRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/movie/MovieRepositoryImpl.kt
  data/src/main/java/com/london/data/repository/tvshow/TvShowRepositoryImpl.kt
  data/src/main/java/com/london/data/utils/appPreferences.kt
  data/src/main/java/com/london/data/utils/extensions.kt
  data/src/main/java/com/london/data/utils/loadFromCacheOrFetch.kt
  data/src/test/java/com/london/data/repository/AuthenticationRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/SearchRepositoryImplTest.kt
  data/src/test/java/com/london/data/repository/account/AccountRepositoryImplTest.kt
  presentation/src/main/java/com/london/presentation/feature/account/AccountViewModel.kt
  presentation/src/main/java/com/london/presentation/utils/searchUtils.kt
  presentation/src/test/java/com/london/presentation/feature/account/account/AccountViewModelTest.kt
Labels: enhancement
